### ISSUE TITLE
Unreadable test result

### ISSUE THREAD

**Issue by evis** [buildbuddy-io/buildbuddy#6453] opened 2024-04-26 12:18 UTC
Test result is quite unreadable sometimes.

**Screenshots**

<img width="1158" alt="Screenshot 2024-04-26 at 15 14 50" src="https://github.com/buildbuddy-io/buildbuddy/assets/23415191/847c5b69-42a1-481b-97c1-55262cbb3920">

Test log: [build_logs.txt](https://github.com/buildbuddy-io/buildbuddy/files/15130523/build_logs.txt)

**Comment by bduffany** [comment] 2024-04-26 13:53
Hi, do you have a public link to this invocation that you could share (or DM me in our Slack channel)? Or alternatively, do you mind downloading the test.xml file from that page and attaching it here?

![image](https://github.com/buildbuddy-io/buildbuddy/assets/2414826/961dc471-7c15-431b-9e7b-9b51166a1c7a)

**Comment by evis** [comment] 2024-04-27 05:08
Sure, here it is: [test.xml.zip](https://github.com/buildbuddy-io/buildbuddy/files/15137097/test.xml.zip)

**Comment by evis** [comment] 2024-05-15 08:25
@bduffany is given test.xml helpful? Maybe, something else needed?

**Comment by bduffany** [comment] 2024-05-15 14:00
The problematic part from the snippet that Son showed is this part:

```
<failure 
      message="Unexpected not mocked invocation getLatestResult(car_info {&amp;#010;  mark: &quot;
```

note that the message contains entities like `&amp;#010;` etc.

I don't have a ton of experience with these XML files and hoping other folks can chime in if they have more experience with this, but from reading the XML schema documentation [here](https://windyroad.com.au/dl/Open%20Source/JUnit.xsd) I think the `message` field (assert message) is intended for a short summary of the error, while the body of that XML tag should contain the full error. It appears that in the XML doc you provided, the same full error message is included in both the `message` attribute and the body of the tag.

Which bazel test rules are you using? is it just `java_test` or something else? Also what test library are you using? (What does the code for the failing assertion look like?) Having this info would help us understand this a little better and possibly reproduce it.

**Comment by sluongng** [comment] 2024-05-15 14:39
Given @evis profile, I think it's from rules_scala with https://github.com/bazelbuild/rules_scala/blob/e2fe29c3b51647ecd07a562917c2c09fb48f9c0a/scala/support/JUnitXmlReporter.scala#L412-L437

**Comment by sluongng** [comment] 2024-05-15 15:39
A quick fix that I could think of is to patch rules_scala so that the `message` attribute will only include the first line of `failure.message`. That will give you a much more readable error with Junit XML and Bazel (and BuildBuddy).

@evis could you please open an issue on rules_scala to report this? I think rules_scala maintainers would have more context on how `scalatest` runner created these events, as well as best practices from other Scala build tools to replicate over.

**Comment by brentleyjones** [comment] 2024-05-15 15:41
Since this is XML, shouldn't the entities be translated correctly when displayed? So `&amp;` should become `&`.

**Comment by sluongng** [comment] 2024-05-15 15:58
Yeah, I think it's encoded twice. Once in rules_scala for `\n` to become `&#10;`, then the second time for `&` into `&amp;`, resulting in `&amp;#10;`.

We could reverse these operations on our end. However, it does not change the fact that rules_scala is being silly, fitting a huge stack trace into the `message` attribute of `<failure>...</failure>`. The same error + stack trace is again shoved into the text body inside this tag, which duplicates the content.

I think the correct fix here is to ensure that `message` only uses the first line in `TestFailed` event of scalatest. That way there would be no new line to encode/decode. We are still displaying the stack trace from the text body below.

Ima close this as not planned. We could reopen the issue if there is a valid use case for new line characters inside these XML attributes.

**Closed by sluongng** 2024-05-15 15:58 UTC
