### ISSUE TITLE
WRN Disconnecting invocation "5cb......": rpc error: code = Canceled desc = context canceled invocation_id=5cb1e... request_id=1556b...

### ISSUE THREAD

**Issue by mailbox171** [buildbuddy-io/buildbuddy#4481] opened 2023-08-04 08:24 UTC
Hello, we started getting these errors.
After few hours container was restarted.
Restart seems ok, but these warning are still these.

Thanks a lot

Clients have errors

```bash
2023-08-04 06:43:44.023748 | node | INFO: Invocation ID: 6a8e736d-7a67-4408-8ce3-82683504c8fc
2023-08-04 06:43:44.026857 | node | ERROR: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: hostname/10.53.229.10:80
2023-08-04 06:43:44.026891 | node | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
```

This is BB log

```bash
$ kubectl logs buildbuddy-app-0   -n buildbuddy --previous | grep WRN
2023/07/28 08:29:32.123 WRN Disconnecting invocation "5cb1e519-5d3b-4a89-a4ed-cd9b5396e440": rpc error: code = Canceled desc = context canceled invocation_id=5cb1e519-5d3b-4a89-a4ed-cd9b5396e440 request_id=1556b4d3-8a60-47f2-b024-0164aaf934ca
2023/07/28 08:33:35.156 WRN Disconnecting invocation "7ec9edf2-7c57-42ee-bd53-dac645b627e8": rpc error: code = Canceled desc = context canceled invocation_id=7ec9edf2-7c57-42ee-bd53-dac645b627e8 request_id=d190a120-2cf8-4aab-96d9-c0496c0f28a1
2023/07/28 08:38:44.493 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=50f37332-faae-485b-9034-e8de6e629c9c request_id=4aeb5d2f-aaf9-4ba8-8416-30c5b8f89f52
2023/07/28 08:39:06.088 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=951b02ba-f14b-484b-bab3-6db1cf09383d request_id=0ec83d27-3a55-46fc-a5e4-61d84d80f973
2023/07/28 08:53:17.779 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=86610c3a-bbd2-41d6-a447-df7c4c74b5cc request_id=21d7a18b-7dd9-4201-9242-25ee1e76cf50
2023/07/28 09:22:30.606 WRN Error finalizing invocation "91671034-f25b-4e6e-a06d-3cfd851c8475": rpc error: code = Canceled desc = Attempt 1 of invocation 91671034-f25b-4e6e-a06d-3cfd851c8475 pre-empted by more recent attempt, invocation not finalized. invocation_id=91671034-f25b-4e6e-a06d-3cfd851c8475 request_id=4a085d47-be4f-4c7b-b315-838aef8f596c
2023/07/28 09:28:07.894 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=6a509abc-8abe-4f8f-9fb0-969754e7828e request_id=45b607a1-ab22-4fa3-a204-e4aff81cfa4b
2023/07/28 09:28:22.275 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=1173a284-9483-4722-bce5-e7130b6505ca request_id=c2faa6f0-0ef0-43d5-90ed-0518bb2f8aac
2023/07/28 09:30:31.098 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=8771062f-0e6a-487a-b62b-7a24c8350cd8 request_id=fcf39232-3492-47fc-b9d4-46a73c61d887
2023/07/28 09:33:43.201 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=58fe29ee-3344-46f9-a992-a80ad588c0ef request_id=0c54e7a9-58a4-4dbd-b025-0954878da4a0
2023/07/28 09:34:35.127 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=8249cb47-1554-4e53-b70c-afbbb8c9cf6a request_id=7fe4f272-b894-4ae1-8185-b38507d7c2dd
2023/07/28 09:37:08.239 WRN Disconnecting invocation "0a9f834d-e8e0-4b68-889f-e425f1d94eee": rpc error: code = Canceled desc = context canceled invocation_id=0a9f834d-e8e0-4b68-889f-e425f1d94eee request_id=93e6d5ee-5fb6-4dde-bd38-8032aed2d23e
2023/07/28 09:37:08.244 WRN Reporting disconnected status for invocation invocation_attempt=1 invocation_id=0a9f834d-e8e0-4b68-889f-e425f1d94eee request_id=93e6d5ee-5fb6-4dde-bd38-8032aed2d23e
```

**Comment by mailbox171** [comment] 2023-08-04 09:35
Now all error we are getting is

Attempt 1 of invocation  pre-empted by more recent attempt

**Comment by sluongng** [comment] 2023-08-04 09:50
Hey @mailbox171,

IIRC, you are running the OSS BuildBuddy on-prem? Do you happen to know which version of BuildBuddy are you on?

It seems like the error you are getting was
```
Attempt <n> of invocation <uuid> pre-empted by more recent attempt, invocation not finalized
```
is it correct?

That error seems to come from https://github.com/buildbuddy-io/buildbuddy/blob/f5cdc999c2f6f51de5e15053c2936411cbcd9e5c/server/build_event_protocol/build_event_handler/build_event_handler.go#L786-L793 which runs a SQL query here https://github.com/buildbuddy-io/buildbuddy/blob/f5cdc999c2f6f51de5e15053c2936411cbcd9e5c/server/backends/invocationdb/invocationdb.go#L112 and returning if affected rows is more than zero.

IIRC you are connecting BuildBuddy with MariaDB on-prem? Is it possible for you to inspect if there is a problem in the DB layer when updating the row with `invocation_id = <uuid> and attempt = <n>`?

**Comment by mailbox171** [comment] 2023-08-04 09:53
I am running on kubernetes.

Logs in mysql pod don't show anything

**Comment by mailbox171** [comment] 2023-08-04 11:31
About dabase. We don't have errors. The metric value is 4 and it does not increase at all

# HELP buildbuddy_sql_error_count Number of SQL queries that resulted in an error.
# TYPE buildbuddy_sql_error_count counter
buildbuddy_sql_error_count{sql_query_template="upsert_invocation"} 4

**Comment by mailbox171** [comment] 2023-08-04 12:22
VERSION IS v2.12.39 



kubectl logs buildbuddy-app-0   -n buildbuddy -f
2023/08/04 09:45:47.615 INF BuildBuddy v2.12.39 (7c2fd2d621c07fdfa3accbec714862be2c25b07e) compiled with go1.20.3 X:nocoverageredesign
2023/08/04 09:45:47.615 INF Reading buildbuddy config from '/data/buildbuddy/config.yml'
2023/08/04 09:45:47.622 INF Auto-migrating DB
2023/08/04 09:45:47.732 INF Cache: BuildBuddy cache API enabled!
2023/08/04 09:45:50.620 INF HealthChecker transitioning from ready: false => ready: true

2023/08/04 09:45:51 server/util/db/db.go:564 SLOW SQL >= 500ms
[3391.283ms] [rows:1] 
		SELECT 
			COUNT(DISTINCT invocation_id) as invocation_count,
			COUNT(DISTINCT host) as bazel_host_count,
			COUNT(DISTINCT user) as bazel_user_count
		FROM "Invocations" as i
		WHERE 
			i.created_at_usec >= 1691020800000000 AND
			i.created_at_usec < 1691107200000000
2023/08/04 09:45:51.285 INF Enabling monitoring (pprof/prometheus) interface on http://0.0.0.0:9090
2023/08/04 09:45:51.286 INF gRPC listening on 0.0.0.0:1987
2023/08/04 09:45:51.286 INF gRPC listening on 0.0.0.0:1985
2023/08/04 09:45:51.286 INF 
2023/08/04 09:45:51.286 INF Your BuildBuddy server is running!
2023/08/04 09:45:51.286 INF 
2023/08/04 09:45:51.286 INF Add the following lines to your .bazelrc to start sending build events to your local server:
2023/08/04 09:45:51.286 INF     build --bes_results_url=http://localhost:8080/invocation/
2023/08/04 09:45:51.286 INF     build --bes_backend=grpc://localhost:1985
2023/08/04 09:45:51.286 INF 
2023/08/04 09:45:51.286 INF You can now view BuildBuddy in the browser.
2023/08/04 09:45:51.286 INF     http://localhost:8080/
2023/08/04 09:46:05.508 INF Created invocation "1eac600b-a36f-4300-8b2f-b99288eb576b", attempt 1 invocation_attempt=1 invocation_id=1eac600b-a36f-4300-8b2f-b99288eb576b request_id=1d24989c-36c9-47f1-ae2d-6682980ffbc7
2023/08/04 09:46:06.394 INF Created invocation "54c2f489-bade-45b6-a37e-a969d2d79bc3", attempt 1 invocation_attempt=1 invocation_id=54c2f489-bade-45b6-a37e-a969d2d79bc3 request_id=2758b403-81fb-47e7-a760-c897e1670c21

**Comment by sluongng** [comment] 2023-08-04 13:34
If possible, I would advise you to upgrade to our latest release [v2.16.0](https://github.com/buildbuddy-io/buildbuddy/releases/tag/v2.16.0). Since v2.12.39, we have shipped some improvements toward the Build Event Handler such as #3998 and #4094.

What is curious to me though, is this log
```
Attempt <n> of invocation <uuid> pre-empted by more recent attempt, invocation not finalized
```
would only happen when bad network conditions happen that cause Bazel to lose connection with the server and thus, retried sending the event stream 🤔 

You also said the BuildBuddy container was restarted. Was that a manual intervention or did your pod crash and get automatically rescheduled by K8s? It would be interesting to get more information on the state of the pod when the client was having the problem like you described above.
```
2023-08-04 06:43:44.023748 | node | INFO: Invocation ID: 6a8e736d-7a67-4408-8ce3-82683504c8fc
2023-08-04 06:43:44.026857 | node | ERROR: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: hostname/10.53.229.10:80
2023-08-04 06:43:44.026891 | node | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
```

Worth to note here that our app log should come with an invocation ID, so you should be able to find relevant logs by grep for the invocation ID above.

**Comment by mailbox171** [comment] 2023-08-04 14:45
The typical invocation, when it goes wrong, looks like this


$ kubectl logs buildbuddy-app-0   -n buildbuddy | grep 872a4409-ebf6-41f3-9b91-93c01bdfb7e8
2023/08/04 14:28:47.020 WRN Error finalizing invocation "872a4409-ebf6-41f3-9b91-93c01bdfb7e8": rpc error: code = Canceled desc = Attempt 1 of invocation 872a4409-ebf6-41f3-9b91-93c01bdfb7e8 pre-empted by more recent attempt, invocation not finalized. invocation_id=872a4409-ebf6-41f3-9b91-93c01bdfb7e8 request_id=584f9b14-027a-4784-8187-e27c8117da86
2023/08/04 14:28:48.075 WRN Error finalizing invocation "872a4409-ebf6-41f3-9b91-93c01bdfb7e8": rpc error: code = Canceled desc = Attempt 1 of invocation 872a4409-ebf6-41f3-9b91-93c01bdfb7e8 pre-empted by more recent attempt, invocation not finalized. invocation_id=872a4409-ebf6-41f3-9b91-93c01bdfb7e8 request_id=287e5ae2-a012-450d-aebe-26394820fea9
2023/08/04 14:28:49.730 WRN Error finalizing invocation "872a4409-ebf6-41f3-9b91-93c01bdfb7e8": rpc error: code = Canceled desc = Attempt 1 of invocation 872a4409-ebf6-41f3-9b91-93c01bdfb7e8 pre-empted by more recent attempt, invocation not finalized. invocation_id=872a4409-ebf6-41f3-9b91-93c01bdfb7e8 request_id=36361497-72fa-4ac5-9eb9-5111f7bc45d3
2023/08/04 14:28:52.345 WRN Error finalizing invocation "872a4409-ebf6-41f3-9b91-93c01bdfb7e8": rpc error: code = Canceled desc = Attempt 1 of invocation 872a4409-ebf6-41f3-9b91-93c01bdfb7e8 pre-empted by more recent attempt, invocation not finalized. invocation_id=872a4409-ebf6-41f3-9b91-93c01bdfb7e8 request_id=37258471-d99c-449d-89de-0f6c0f0a25af
2023/08/04 14:28:56.498 WRN Error finalizing invocation "872a4409-ebf6-41f3-9b91-93c01bdfb7e8": rpc error: code = Canceled desc = Attempt 1 of invocation 872a4409-ebf6-41f3-9b91-93c01bdfb7e8 pre-empted by more recent attempt, invocation not finalized. invocation_id=872a4409-ebf6-41f3-9b91-93c01bdfb7e8 request_id=2565758e-b94d-44a5-b276-48485923e9a6

**Comment by siggisim** [comment] 2023-08-04 15:23
This looks like the client is attempting to make a build event stream connection to the server, but failing and then retrying - all of those log lines look expected for that scenario.

The question is why is the stream getting disconnected? Are you running behind a load balancer / ingress?

**Comment by mailbox171** [comment] 2023-08-04 16:04
Hello, thanks:

No Ingress:
Just TCP load balancing
And probes between LB and BB pod are 100% ok

So I guess networking issue between LB and Bazel client

**Comment by mailbox171** [comment] 2023-08-04 22:10
We also see connection-refused exception in the client




ser@lx0345972:/workspace/ddad$ bazel build --config=adp_focal_run_abc_offsite --experimental_ui_max_stdouterr_bytes=-1 --nobuild_runfile_links --announce_rc --keep_going=false --remote_cache=grpc://build-cache.adx.abcgroup.com:80/cache-focal -- //platform/aas/intc/machinestatemanager:abc_msm_machine_state_manager //platform/aas/ara/diag_mediator/... //platform/aas/intc/aurixSim/... //platform/aas/intc/environmentwatchdog:environment_watchdog_server_app //platform/aas/intc/psl:psl //platform/aas/intc/psn:psn //platform/aas/intc/timesyncclient:TimeSyncClient //platform/aas/pas/crashdumphandler:CrashDumpHandler //platform/aas/pas/phmwatchdogclient:PHMWatchdogClient //platform/aas/tools/deployment/docker:run_docker
INFO: Invocation ID: 3022e469-a4fd-4b20-b796-ec0f2bb02000
ERROR: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: build-cache.adx.abcgroup.com/10.53.229.10:80
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
    at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
    at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
    at io.netty.channel.unix.Socket.finishConnect(Socket.java:320)
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Unknown Source)

 

ERROR: Failed to query remote execution capabilities: finishConnect(..) failed: Connection refused: build-cache.adx.abcgroup.com/10.53.229.10:80

**Comment by mailbox171** [comment] 2023-08-05 16:36
For "Error finalizing invocation" affected identifiers, there is never a "Created invocation" message before.
What does it mean?
Maybe the creation fails without loggin a message?
Thanks


$ kubectl logs buildbuddy-app-0   -n buildbuddy | grep 920c7179-01f9-44ea-af6b-488e0d6e55a7
2023/08/05 16:21:15.261 WRN Error finalizing invocation "920c7179-01f9-44ea-af6b-488e0d6e55a7": rpc error: code = Canceled desc = Attempt 1 of invocation 920c7179-01f9-44ea-af6b-488e0d6e55a7 pre-empted by more recent attempt, invocation not finalized. invocation_id=920c7179-01f9-44ea-af6b-488e0d6e55a7 request_id=77c73e99-735b-48e1-871d-90ab9a64bc6f
2023/08/05 16:21:16.265 WRN Error finalizing invocation "920c7179-01f9-44ea-af6b-488e0d6e55a7": rpc error: code = Canceled desc = Attempt 1 of invocation 920c7179-01f9-44ea-af6b-488e0d6e55a7 pre-empted by more recent attempt, invocation not finalized. invocation_id=920c7179-01f9-44ea-af6b-488e0d6e55a7 request_id=ce36f894-6e04-4d1b-a41f-418438a690e3
2023/08/05 16:21:17.870 WRN Error finalizing invocation "920c7179-01f9-44ea-af6b-488e0d6e55a7": rpc error: code = Canceled desc = Attempt 1 of invocation 920c7179-01f9-44ea-af6b-488e0d6e55a7 pre-empted by more recent attempt, invocation not finalized. invocation_id=920c7179-01f9-44ea-af6b-488e0d6e55a7 request_id=985d6644-3b69-46e4-ac90-f455f570121e
2023/08/05 16:21:20.434 WRN Error finalizing invocation "920c7179-01f9-44ea-af6b-488e0d6e55a7": rpc error: code = Canceled desc = Attempt 1 of invocation 920c7179-01f9-44ea-af6b-488e0d6e55a7 pre-empted by more recent attempt, invocation not finalized. invocation_id=920c7179-01f9-44ea-af6b-488e0d6e55a7 request_id=80ea6e50-f61f-4188-bf0f-371dbbe2d53f
2023/08/05 16:21:24.534 WRN Error finalizing invocation "920c7179-01f9-44ea-af6b-488e0d6e55a7": rpc error: code = Canceled desc = Attempt 1 of invocation 920c7179-01f9-44ea-af6b-488e0d6e55a7 pre-empted by more recent attempt, invocation not finalized. invocation_id=920c7179-01f9-44ea-af6b-488e0d6e55a7 request_id=fb182604-f73f-45d8-b8db-388f6ae65d99

**Comment by sluongng** [comment] 2023-08-07 14:28
@mailbox171 I seems to be able to reproduce the problem where no `Created invocation` is printed when the Cache was configured wrongly.

If you use [--remote_grpc_log](https://bazel.build/reference/command-line-reference#flag--remote_grpc_log), what does the GetCapabilities response look like?
For example, with a broken remote cache config, I would get something like this

```
!?master ~/work/buildbuddy/buildbuddy> bazel build cli --config=local --remote_grpc_log=grpc.log
INFO: Invocation ID: 61352a6d-2851-47d1-b771-dd67591ac0ad
ERROR: Cannot use hash function SHA256 with remote cache. Server supported functions are: []
INFO: Streaming build results to: http://localhost:8080/invocation/61352a6d-2851-47d1-b771-dd67591ac0ad
exit 34

!?master ~/work/buildbuddy/buildbuddy> bb print --grpc_log=grpc.log
{
  "metadata":  {
    "toolDetails":  {
      "toolName":  "bazel",
      "toolVersion":  "6.3.1"
    },
    "actionId":  "capabilities",
    "toolInvocationId":  "61352a6d-2851-47d1-b771-dd67591ac0ad",
    "correlatedInvocationsId":  "2ea80b47-606a-4cef-8a12-9b724a0eed93"
  },
  "status":  {},
  "methodName":  "build.bazel.remote.execution.v2.Capabilities/GetCapabilities",
  "details":  {
    "getCapabilities":  {
      "request":  {},
      "response":  {
        "lowApiVersion":  {
          "major":  2
        },
        "highApiVersion":  {
          "major":  2,
          "minor":  3
        }
      }
    }
  },
  "startTime":  "2023-08-07T14:24:29.194Z",
  "endTime":  "2023-08-07T14:24:29.196Z"
}
```

and the server log would look something like this

```
2023/08/07 16:24:29.206 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=68d34543-1a29-4872-ab1b-1ceb3e7b073b
2023/08/07 16:24:30.218 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=d16c40e5-89b5-4ba4-bae8-6c06baf6276c
2023/08/07 16:24:31.833 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=859ba649-2f7c-4d5b-80de-a472eb7b9d91
2023/08/07 16:24:34.406 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=50447dea-6d08-4eb7-b846-6da876f3764c
2023/08/07 16:24:38.514 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=b113c538-cdd4-47da-9e61-01341c3039b6
```

Is it possible for you to share with us your current BuildBuddy config.yaml? Or your k8s values.yaml?

**Comment by mailbox171** [comment] 2023-08-08 11:12
We are now seeing this more like a networking problem.
We always the this 3-frame pattern when it occurs

![MicrosoftTeams-image (2)](https://github.com/buildbuddy-io/buildbuddy/assets/31764337/b95fff14-099f-4f12-8970-cf601e3f2ec9)
![MicrosoftTeams-image (1)](https://github.com/buildbuddy-io/buildbuddy/assets/31764337/8098c5fe-e806-4b3b-9851-ab715967e4dd)
![MicrosoftTeams-image](https://github.com/buildbuddy-io/buildbuddy/assets/31764337/b8306664-c4b7-4fd9-bddb-a25ea43a3138)

**Comment by mailbox171** [comment] 2023-08-08 12:43
Our config is always the same. It worked of for 3 months



cleanup_workers: 3
database:
  data_source: "mysql://xkxLzPTLWq~!bBoSZZ:v/Z4jzB|rI!i5OdPhy@tcp(buildbuddy-mysql-svc)/buildbuddy"
storage:
  ttl_seconds: 2592000 # 30 days
  chunk_file_size_bytes: 3000000  # 3 MB
  disk:
    root_directory: "/data/blobs/"
cache:
  max_size_bytes: 1500000000000 # 1500 GB
  disk:
    use_v2_layout: true
    root_directory: "/data/cache/"
# app:
#   log_level: debug
#   enable_structured_logging: true
#   l og_include_short_file_name: true

**Comment by mailbox171** [comment] 2023-08-08 18:59
> @mailbox171 I seems to be able to reproduce the problem where no `Created invocation` is printed when the Cache was configured wrongly.
> 
> If you use [--remote_grpc_log](https://bazel.build/reference/command-line-reference#flag--remote_grpc_log), what does the GetCapabilities response look like? For example, with a broken remote cache config, I would get something like this
> 
> ```
> !?master ~/work/buildbuddy/buildbuddy> bazel build cli --config=local --remote_grpc_log=grpc.log
> INFO: Invocation ID: 61352a6d-2851-47d1-b771-dd67591ac0ad
> ERROR: Cannot use hash function SHA256 with remote cache. Server supported functions are: []
> INFO: Streaming build results to: http://localhost:8080/invocation/61352a6d-2851-47d1-b771-dd67591ac0ad
> exit 34
> 
> !?master ~/work/buildbuddy/buildbuddy> bb print --grpc_log=grpc.log
> {
>   "metadata":  {
>     "toolDetails":  {
>       "toolName":  "bazel",
>       "toolVersion":  "6.3.1"
>     },
>     "actionId":  "capabilities",
>     "toolInvocationId":  "61352a6d-2851-47d1-b771-dd67591ac0ad",
>     "correlatedInvocationsId":  "2ea80b47-606a-4cef-8a12-9b724a0eed93"
>   },
>   "status":  {},
>   "methodName":  "build.bazel.remote.execution.v2.Capabilities/GetCapabilities",
>   "details":  {
>     "getCapabilities":  {
>       "request":  {},
>       "response":  {
>         "lowApiVersion":  {
>           "major":  2
>         },
>         "highApiVersion":  {
>           "major":  2,
>           "minor":  3
>         }
>       }
>     }
>   },
>   "startTime":  "2023-08-07T14:24:29.194Z",
>   "endTime":  "2023-08-07T14:24:29.196Z"
> }
> ```
> 
> and the server log would look something like this
> 
> ```
> 2023/08/07 16:24:29.206 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=68d34543-1a29-4872-ab1b-1ceb3e7b073b
> 2023/08/07 16:24:30.218 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=d16c40e5-89b5-4ba4-bae8-6c06baf6276c
> 2023/08/07 16:24:31.833 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=859ba649-2f7c-4d5b-80de-a472eb7b9d91
> 2023/08/07 16:24:34.406 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=50447dea-6d08-4eb7-b846-6da876f3764c
> 2023/08/07 16:24:38.514 WRN Error finalizing invocation "61352a6d-2851-47d1-b771-dd67591ac0ad": rpc error: code = Canceled desc = Attempt 1 of invocation 61352a6d-2851-47d1-b771-dd67591ac0ad pre-empted by more recent attempt, invocation not finalized. invocation_id=61352a6d-2851-47d1-b771-dd67591ac0ad request_id=b113c538-cdd4-47da-9e61-01341c3039b6
> ```
> 
> Is it possible for you to share with us your current BuildBuddy config.yaml? Or your k8s values.yaml?

é 
j
 
 bazel  5.3.1  capabilities $c11e0118-7d2d-4fa5-8d33-28c93cc4a835"$58f2ee6f-8317-4d74-9e15-da09a9fb2253 ›    – io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: build-cache.adx.fcagroup.com/10.53.229.10:80 <build.bazel.remote.execution.v2.Capabilities/GetCapabilities" b 
 *
 ¡òÈ¦  €¿Ö 2  ­òÈ¦  À«Á›

**Comment by sluongng** [comment] 2023-08-09 09:29
@mailbox171 your app config looks fine to me. I think you are on point with the diagnosis: if you connect direct to the pod and had so issue, the problem must be on the LB/Ingress layer. 

What are you using for ingress? We recommend nginx in our helm chart https://github.com/buildbuddy-io/buildbuddy-helm/blob/master/charts/buildbuddy/templates/ingress.yaml.

**Comment by sluongng** [comment] 2023-08-17 12:25
I am closing this issue for now as we identified the issue originated from the user's proxy layer which we don't manage.

**Closed by sluongng** 2023-08-17 12:24 UTC
