### ISSUE TITLE
`duplicate key value violates unique constraint "Invocations_pkey"`

### ISSUE THREAD

**Issue by nhurden** [buildbuddy-io/buildbuddy#4349] opened 2023-07-19 04:16 UTC
Occasionally BEP uploads fail with:
```
The Build Event Protocol upload failed: Not retrying publishBuildEvents, no more attempts left: 
status='Status{code=UNKNOWN, description=ERROR: duplicate key value violates unique constraint "Invocations_pkey" (SQLSTATE 23505), cause=null}' 
UNKNOWN: 
UNKNOWN: 
ERROR: duplicate key value violates unique constraint "Invocations_pkey" (SQLSTATE 23505) 
UNKNOWN: 
UNKNOWN: 
ERROR: duplicate key value violates unique constraint "Invocations_pkey" (SQLSTATE 23505)
```
(line breaks added manually)

Logs on the server side point to https://github.com/buildbuddy-io/buildbuddy/blob/v2.12.46/server/util/db/db.go#L759

Using v2.12.46 with postgres

**Comment by siggisim** [comment] 2023-07-27 23:20
Hey @nhurden - thanks for reporting!

Does this reproduce with latest `v2.15.0`?

I suspect this is an edge case we handle gracefully in MySQL, but we don't handle correctly with the Postgres driver.

cc @tempoz

**Comment by nhurden** [comment] 2023-07-28 11:24
Could this be related to https://github.com/buildbuddy-io/buildbuddy/blob/master/server/util/db/db_cgo.go#L28? Seems to handle MySQL and SQLite but not PostgreSQL.

**Comment by siggisim** [comment] 2023-07-28 16:12
That looks like a good bet!

**Comment by tempoz** [comment] 2023-07-31 17:54
I'll add postgres to that function; guess I missed it the first time :P

**Comment by siggisim** [comment] 2023-08-01 00:45
Should be fixed in the next release by: https://github.com/buildbuddy-io/buildbuddy/pull/4437

**Closed by siggisim** 2023-08-01 00:45 UTC
