### ISSUE TITLE
No results when using BuildFarm remote execution locally

### ISSUE THREAD

**Issue by mihaigalos** [buildbuddy-io/buildbuddy#100] opened 2020-10-11 16:23 UTC
I'm trying to run [`bazelbuild/buildfarm`](https://github.com/bazelbuild/bazel-buildfarm) by spinning up a server and a worker locally.
I am compiling [`mihaigalos/osi_stack`](https://github.com/mihaigalos/osi_stack) and have remote execution up and running, including caching:

```bash
➜  osi_stack git:(master) bazel clean --async --expunge && bazel test --bes_results_url=http://localhost:8080/invocation/ --bes_backend=grpc://localhost:1985 --remote_executor=grpc://localhost:8980 //...
...
INFO: Analyzed 27 targets (22 packages loaded, 373 targets configured).
INFO: Found 2 targets and 25 test targets...
INFO: Elapsed time: 19.066s, Critical Path: 0.77s
INFO: 100 processes: 100 remote cache hit.
```

There is currently no way to have remote execution statistics from buildfarm back into buildbuddy, is there?

**Comment by siggisim** [comment] 2020-10-12 16:56
Hey Mihai - just tried to reproduce this locally, and got the BuildBuddy URL printed at the end of the execution with BuildFarm, and all of the performance profiling information on the Timing tab seems to work.

Are there any execution statistics in particular from BuildFarm that you'd like to see back in BuildBuddy?

**Comment by siggisim** [comment] 2020-10-12 20:01
Hey @mihaigalos - the cache tab won't be populated unless you're using the BuildBuddy cache, because we need extra hooks that aren't provided to us by Bazel's BEP.

The timing tab should work as long as BuildBuddy can communicate with the gRPC cache you're using. If you're using Docker to run BuildBuddy - you'll probably need to pass the `--network host` [flag](https://docs.docker.com/network/host/) into your Docker invocation to allow BuildBuddy to communicate with BuildFarm's cache.

**Comment by mihaigalos** [comment] 2020-10-13 19:51
Hi @siggisim  - this is so cool! Indeed the timing works with the docker flag.
If you think no further action can be performed here in the form of a feature request, we can close this Issue! :+1:

**Comment by mihaigalos** [comment] 2020-10-14 03:49
btw: Please give me a reference of where in the code you consume the data for the cache tab.
I assume you store some metadata via a gRPC channel and then display it?

I'll have a look at the BEP implementation and consider extending it.

**Comment by siggisim** [comment] 2020-10-14 18:45
Hey @mihaigalos - glad that fixed the issue, and that you like the timing tab!

I've added some documentation about the `--network` flag in https://github.com/buildbuddy-io/buildbuddy/commit/5678d388fb22e36796772f3436ff98781477bb02 so hopefully others can avoid bumping into this issue.

As for displaying the data on the cache tab - we currently manually track all of the requests made to the BuildBuddy cache and store them per invocation. It would be tricky to support third party caches in this way, but if we were provided this data via the BEP - we could certainly display it by populating the right fields in the invocation proto: https://github.com/buildbuddy-io/buildbuddy/blob/cb58edbc7334915d405461f141e926e90bebda02/server/build_event_protocol/build_event_handler/build_event_handler.go#L136

Going to close this one since we figured out the original issue! Feel free to file a feature request or ping me on Slack if you want to discuss the cache stuff further.

**Closed by siggisim** 2020-10-14 18:45 UTC
